language: rust
cache: cargo
os: 
  - linux
rust:
- stable
- beta
- nightly
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

before_script:
  - |
      cargo install --force cargo-travis &&
      export PATH=$HOME/.cargo/bin:$PATH
script:
  - |
    cargo build --all --verbose &&
    cargo test --all --verbose &&
    cargo bench --all --verbose &&
    cargo --only stable doc

after_success:
  - |
      cargo coveralls --verbose &&
      cargo coverage -m ../kcov --all
      bash <(curl -s https://codecov.io/bash)

env:
  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly

sudo: false
matrix:
allow_failure:
- rust: nightly
